### ISSUE TITLE
Is it Kotlin Multiplatform compatible?

### ISSUE THREAD

**Issue by Andrew0000** [Chafficui/KPhysics#1]
If not, is there a plan to make it multiplatform compatible?

**Comment by Chafficui** [comment]
@Andrew0000 I haven't tested it, but it uses no 3rd Party libraries and is in plain kotlin, so it should be.

**Comment by Andrew0000** [comment]
Thank you for the response. 
As I understand, it's released on jitpack and wasn't compiled for different platforms. I suppose it would be useful to do a migration to KMP with a few most popular targets like Android, Desktop, IOS.
By the way there is how I migrated my Android/Kotlin library to KMP, may be helpful if you decide to do it: 
https://medium.com/mobilepeople/migration-of-android-library-to-kotlin-multiplatform-d3b7e7e18f44

**Comment by Chafficui** [comment]
Hey @Andrew0000,
if you need this project in one of yours, feel free to convert it using your guide. :) I will merge your pull request if you'd like to.
If not, please close this issue :)
